import { useEffect, useMemo, useState } from 'react';
import { BarChart3, Boxes, ClipboardList, Edit3, Leaf, Package, Plus, Search, ShoppingBag, Trash2, Truck, Users, Warehouse, X } from 'lucide-react';
import { useApp } from '../context/AppContext';
import { adminApi } from '../services/adminApi';
import { useNavigate } from 'react-router-dom';
import '../admin.css';

const tabs = [
  ['dashboard','Dashboard',BarChart3],['products','Products',Package],['plants','Plants',Leaf],['ingredients','Ingredients',Boxes],['mixRules','Mix Rules',Leaf],['inventory','Inventory',Warehouse],['orders','Orders',ShoppingBag],['users','Users',Users],['reports','Reports',ClipboardList]
];
const blank = { products:{name:'',category:'',price:'',stock:'',description:'',image:'',featured:false,active:true}, plants:{name:'',scientificName:'',category:'',environment:'Indoor',description:'',image:'',active:true}, ingredients:{name:'',category:'',description:'',pricePerKg:'',stockQuantity:'',minimumStock:'',unit:'kg',active:true} };
const money = n => `₹${Number(n||0).toLocaleString('en-IN',{maximumFractionDigits:2})}`;

function Modal({title,onClose,children}){return <div className="adminModalBackdrop"><div className="adminModal"><div className="adminModalHead"><h3>{title}</h3><button onClick={onClose}><X size={19}/></button></div>{children}</div></div>}
function Field({label,children}){return <label className="adminField"><span>{label}</span>{children}</label>}
function CrudModal({type,item,onClose,onSave}){
 const [form,setForm]=useState(item||blank[type]); const update=(k,v)=>setForm(f=>({...f,[k]:v}));
 return <Modal title={`${item?'Edit':'Add'} ${type==='mixRules'?'Mix Rule':type.slice(0,-1)}`} onClose={onClose}>
  <form className="adminForm" onSubmit={e=>{e.preventDefault();onSave(form)}}>
   {type==='products'&&<><Field label="Name"><input required value={form.name||''} onChange={e=>update('name',e.target.value)}/></Field><Field label="Category"><input required value={form.category||''} onChange={e=>update('category',e.target.value)}/></Field><div className="adminTwo"><Field label="Price"><input required type="number" min="0" value={form.price||''} onChange={e=>update('price',Number(e.target.value))}/></Field><Field label="Stock"><input required type="number" min="0" value={form.stock??''} onChange={e=>update('stock',Number(e.target.value))}/></Field></div><Field label="Image URL"><input value={form.image||''} onChange={e=>update('image',e.target.value)}/></Field><Field label="Description"><textarea value={form.description||''} onChange={e=>update('description',e.target.value)}/></Field><label className="check"><input type="checkbox" checked={form.featured!==false} onChange={e=>update('featured',e.target.checked)}/> Featured</label></>}
   {type==='plants'&&<><Field label="Name"><input required value={form.name||''} onChange={e=>update('name',e.target.value)}/></Field><Field label="Scientific name"><input value={form.scientificName||''} onChange={e=>update('scientificName',e.target.value)}/></Field><div className="adminTwo"><Field label="Category"><input required value={form.category||''} onChange={e=>update('category',e.target.value)}/></Field><Field label="Environment (comma separated)"><input value={Array.isArray(form.environment)?form.environment.join(', '):(form.environment||'')} onChange={e=>update('environment',e.target.value)}/></Field></div><Field label="Image URL"><input value={form.image||''} onChange={e=>update('image',e.target.value)}/></Field><Field label="Description"><textarea value={form.description||''} onChange={e=>update('description',e.target.value)}/></Field></>}
   {type==='ingredients'&&<><Field label="Name"><input required value={form.name||''} onChange={e=>update('name',e.target.value)}/></Field><div className="adminTwo"><Field label="Category"><input value={form.category||''} onChange={e=>update('category',e.target.value)}/></Field><Field label="Unit"><input value={form.unit||'kg'} onChange={e=>update('unit',e.target.value)}/></Field></div><div className="adminTwo"><Field label="Price / kg"><input required type="number" min="0" value={form.pricePerKg??''} onChange={e=>update('pricePerKg',Number(e.target.value))}/></Field><Field label="Current stock"><input required type="number" min="0" value={form.stockQuantity??''} onChange={e=>update('stockQuantity',Number(e.target.value))}/></Field></div><Field label="Minimum stock"><input type="number" min="0" value={form.minimumStock??0} onChange={e=>update('minimumStock',Number(e.target.value))}/></Field><Field label="Description"><textarea value={form.description||''} onChange={e=>update('description',e.target.value)}/></Field></>}
   <div className="adminModalActions"><button type="button" className="btn ghost" onClick={onClose}>Cancel</button><button className="btn primary">Save</button></div>
  </form>
 </Modal>
}

export default function Admin(){
 const {user}=useApp(); const nav=useNavigate(); const [tab,setTab]=useState('dashboard'); const [stats,setStats]=useState({}); const [data,setData]=useState({products:[],plants:[],ingredients:[],mixRules:[],inventory:[],orders:[],users:[]}); const [search,setSearch]=useState(''); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [notice,setNotice]=useState(''); const [modal,setModal]=useState(null);
 const [ruleForm,setRuleForm]=useState({name:'',plantId:'',environment:'',category:'',ingredients:[{ingredientId:'',percentage:100}],notes:'',active:true});
 const [orderStatus,setOrderStatus]=useState({});
 useEffect(()=>{if(!user){nav('/login');return;}if(user.role!=='ADMIN'){nav('/');return;}loadStats();},[user]);
 useEffect(()=>{if(user?.role==='ADMIN')loadTab(tab);},[tab]);
 async function loadStats(){try{setLoading(true);setStats((await adminApi.getStats()).data);}catch(e){setError(e.response?.data?.message||'Unable to load dashboard.');}finally{setLoading(false);}}
 async function loadTab(t){if(t==='dashboard'||t==='reports')return;try{setLoading(true);const map={products:'getProducts',plants:'getPlants',ingredients:'getIngredients',mixRules:'getMixRules',inventory:'getInventory',orders:'getOrders',users:'getUsers'};if(t==='mixRules'){const [r,p,i]=await Promise.all([adminApi.getMixRules(),adminApi.getPlants(),adminApi.getIngredients()]);setData(d=>({...d,mixRules:r.data,plants:p.data,ingredients:i.data}));}else{const r=await adminApi[map[t]]();setData(d=>({...d,[t]:r.data}));}}catch(e){setError(e.response?.data?.message||`Unable to load ${t}.`);}finally{setLoading(false);}}
 const refresh=async()=>{await loadStats();await loadTab(tab);};
 const filtered=useMemo(()=>{const arr=data[tab]||[];const q=search.toLowerCase();return arr.filter(x=>JSON.stringify(x).toLowerCase().includes(q));},[data,tab,search]);
 async function save(type,form){try{const payload={...form};if(type==='plants')payload.environment=String(payload.environment||'').split(',').map(x=>x.trim()).filter(Boolean);if(modal?.item){await adminApi[`update${type[0].toUpperCase()+type.slice(1,-1)}`](modal.item._id,payload);}else await adminApi[`create${type[0].toUpperCase()+type.slice(1,-1)}`](payload);setModal(null);setNotice(`${type} saved successfully.`);await refresh();}catch(e){setError(e.response?.data?.message||'Save failed.');}}
 async function remove(type,id){if(!confirm('Deactivate this record?'))return;try{await adminApi[`delete${type[0].toUpperCase()+type.slice(1,-1)}`](id);setNotice('Record deactivated.');await refresh();}catch(e){setError(e.response?.data?.message||'Action failed.');}}
 async function saveRule(e){e.preventDefault();const total=ruleForm.ingredients.reduce((s,x)=>s+Number(x.percentage||0),0);if(Math.abs(total-100)>.001){setError('Mix rule percentages must total exactly 100%.');return;}try{if(modal?.item)await adminApi.updateMixRule(modal.item._id,ruleForm);else await adminApi.createMixRule(ruleForm);setModal(null);setNotice('Mix rule saved.');await refresh();}catch(e){setError(e.response?.data?.message||'Unable to save mix rule.');}}
 function openRule(item){setRuleForm(item?{...item,plantId:item.plantId?._id||item.plantId,ingredients:item.ingredients.map(i=>({ingredientId:i.ingredientId?._id||i.ingredientId,percentage:i.percentage})),environment:item.environment||'',category:item.category||''}:{name:'',plantId:'',environment:'',category:'',ingredients:[{ingredientId:'',percentage:100}],notes:'',active:true});setModal({type:'mixRules',item});}
 async function stock(id,mode){const q=Number(prompt(mode==='set'?'Enter new stock quantity:':'Enter quantity:'));if(!Number.isFinite(q)||q<=0)return;try{await adminApi[mode==='add'?'addStock':mode==='remove'?'removeStock':'setStock'](id,q);setNotice('Inventory updated.');await refresh();}catch(e){setError(e.response?.data?.message||'Inventory update failed.');}}
 async function changeOrder(id){const status=orderStatus[id];if(!status)return;try{await adminApi.updateOrderStatus(id,status);setNotice('Order status updated.');await refresh();}catch(e){setError(e.response?.data?.message||'Order update failed.');}}
 async function changeUser(id,active){try{await adminApi.updateUserStatus(id,active);setNotice('User status updated.');await refresh();}catch(e){setError(e.response?.data?.message||'User update failed.');}}
 const title=tabs.find(x=>x[0]===tab)?.[1]||'Dashboard';
 if(!user||user.role!=='ADMIN')return null;
 return <div className="adminPage"><aside className="adminSidebar"><div className="adminBrand"><Leaf size={20}/> Coco<span>Grow</span><small>ADMIN CONSOLE</small></div><nav>{tabs.map(([key,label,Icon])=><button key={key} className={tab===key?'active':''} onClick={()=>{setTab(key);setSearch('');setError('');}}><Icon size={18}/>{label}</button>)}</nav><button className="adminExit" onClick={()=>nav('/')}><Truck size={17}/> View store</button></aside>
 <main className="adminMain"><div className="adminMobileHead"><b>CocoGrow Admin</b></div>{(error||notice)&&<div className={error?'adminAlert error':'adminAlert success'}>{error||notice}<button onClick={()=>{setError('');setNotice('')}}>×</button></div>}
 {tab==='dashboard'&&<Dashboard stats={stats} loading={loading} orders={data.orders}/>} 
 {['products','plants','ingredients'].includes(tab)&&<ResourceSection tab={tab} title={title} rows={filtered} loading={loading} search={search} setSearch={setSearch} onAdd={()=>setModal({type:tab,item:null})} onEdit={item=>setModal({type:tab,item})} onDelete={id=>remove(tab,id)}/>} 
 {tab==='mixRules'&&<MixRules rows={filtered} plants={data.plants} ingredients={data.ingredients} loading={loading} search={search} setSearch={setSearch} onAdd={()=>openRule()} onEdit={openRule} onDelete={id=>remove('mixRules',id)}/>} 
 {tab==='inventory'&&<Inventory rows={filtered} loading={loading} search={search} setSearch={setSearch} onStock={stock}/>} 
 {tab==='orders'&&<OrdersAdmin rows={filtered} loading={loading} search={search} setSearch={setSearch} status={orderStatus} setStatus={setOrderStatus} onChange={changeOrder}/>} 
 {tab==='users'&&<UsersAdmin rows={filtered} loading={loading} search={search} setSearch={setSearch} onChange={changeUser}/>} 
 {tab==='reports'&&<Reports/>}
 {modal?.type==='products'&&<CrudModal type="products" item={modal.item} onClose={()=>setModal(null)} onSave={f=>save('products',f)}/>} {modal?.type==='plants'&&<CrudModal type="plants" item={modal.item} onClose={()=>setModal(null)} onSave={f=>save('plants',f)}/>} {modal?.type==='ingredients'&&<CrudModal type="ingredients" item={modal.item} onClose={()=>setModal(null)} onSave={f=>save('ingredients',f)}/>} {modal?.type==='mixRules'&&<RuleModal form={ruleForm} setForm={setRuleForm} plants={data.plants} ingredients={data.ingredients} onClose={()=>setModal(null)} onSave={saveRule}/>}</main></div>
}
function Dashboard({stats,loading}){const cards=[['Sales',money(stats.sales),'₹'],['Orders',stats.orders||0,''],['Customers',stats.users||0,''],['Products',stats.products||0,''],['Plants',stats.plants||0,''],['Ingredients',stats.ingredients||0,'']];return <section className="adminContent"><div className="adminTop"><div><span className="eyebrow">ADMIN CONSOLE</span><h1>Store overview.</h1><p>Real-time CocoGrow data from MongoDB.</p></div><span className="adminBadge">● Connected</span></div><div className="statGrid">{cards.map(([n,v])=><div className="stat" key={n}><span>{n}</span><strong>{loading?'…':v}</strong><small>Live database value</small></div>)}</div><div className="adminInsightGrid"><div className="adminCard"><span className="eyebrow">SMART MIX</span><h3>{stats.customMixOrders||0} custom mix orders</h3><p>{stats.lowStockIngredients||0} ingredients currently at or below minimum stock.</p></div><div className="adminCard"><span className="eyebrow">SALES</span><h3>{money(stats.monthlySales)} this month</h3><p>{money(stats.todaySales)} recorded today.</p></div></div></section>}
function Toolbar({search,setSearch,onAdd,label}){return <div className="adminToolbar"><div className="adminSearch"><Search size={17}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search..."/></div>{onAdd&&<button className="btn primary" onClick={onAdd}><Plus size={17}/>{label||'Add new'}</button>}</div>}
function ResourceSection({tab,title,rows,loading,search,setSearch,onAdd,onEdit,onDelete}){return <section className="adminContent"><div className="adminTop"><div><span className="eyebrow">MANAGEMENT</span><h1>{title}</h1><p>Create, update and deactivate {title.toLowerCase()}.</p></div></div><Toolbar search={search} setSearch={setSearch} onAdd={onAdd} label={`Add ${title.slice(0,-1)}`}/><div className="adminTableWrap"><table className="adminTable"><thead><tr>{tab==='products'?<><th>Name</th><th>Category</th><th>Price</th><th>Stock</th></>:tab==='plants'?<><th>Name</th><th>Scientific</th><th>Category</th><th>Environment</th></>:<><th>Name</th><th>Category</th><th>Price/kg</th><th>Stock</th><th>Minimum</th></>}<th>Status</th><th>Actions</th></tr></thead><tbody>{loading?<tr><td colSpan="7">Loading...</td></tr>:rows.map(x=><tr key={x._id}><td><b>{x.name}</b></td>{tab==='products'?<><td>{x.category}</td><td>{money(x.price)}</td><td>{x.stock}</td></>:tab==='plants'?<><td>{x.scientificName||'—'}</td><td>{x.category}</td><td>{Array.isArray(x.environment)?x.environment.join(', '):'—'}</td></>:<><td>{x.category||'—'}</td><td>{money(x.pricePerKg)}</td><td>{x.stockQuantity} {x.unit}</td><td>{x.minimumStock||0}</td></>}<td><span className={`statusPill ${x.active===false?'off':'on'}`}>{x.active===false?'Inactive':'Active'}</span></td><td><button className="iconAction" onClick={()=>onEdit(x)}><Edit3 size={16}/></button><button className="iconAction danger" onClick={()=>onDelete(x._id)}><Trash2 size={16}/></button></td></tr>)}</tbody></table>{!loading&&!rows.length&&<div className="adminEmpty">No records found.</div>}</div></section>}
function MixRules({rows,plants,ingredients,loading,search,setSearch,onAdd,onEdit,onDelete}){return <section className="adminContent"><div className="adminTop"><div><span className="eyebrow">FORMULATION</span><h1>Mix Rules</h1><p>Define the ingredient formula used by Smart Mix.</p></div></div><Toolbar search={search} setSearch={setSearch} onAdd={onAdd} label="Add Mix Rule"/><div className="ruleGrid">{loading?<div>Loading...</div>:rows.map(r=><article className="ruleCard" key={r._id}><div className="ruleHead"><div><span>{r.plantId?.name||'Plant'}</span><h3>{r.name}</h3></div><span className="statusPill on">{r.ingredients.reduce((s,x)=>s+Number(x.percentage||0),0)}%</span></div><div className="ruleIngredients">{r.ingredients.map((i,n)=><div key={n}><span>{i.ingredientId?.name||'Ingredient'}</span><b>{i.percentage}%</b></div>)}</div><div className="ruleActions"><button onClick={()=>onEdit(r)}>Edit</button><button onClick={()=>onDelete(r._id)}>Deactivate</button></div></article>)}</div></section>}
function RuleModal({form,setForm,plants,ingredients,onClose,onSave}){const set=(k,v)=>setForm(f=>({...f,[k]:v}));const updateIng=(i,k,v)=>setForm(f=>({...f,ingredients:f.ingredients.map((x,n)=>n===i?{...x,[k]:v}:x)}));const total=form.ingredients.reduce((s,x)=>s+Number(x.percentage||0),0);return <Modal title="Mix Rule" onClose={onClose}><form className="adminForm" onSubmit={onSave}><Field label="Rule name"><input required value={form.name} onChange={e=>set('name',e.target.value)}/></Field><div className="adminTwo"><Field label="Plant"><select required value={form.plantId} onChange={e=>set('plantId',e.target.value)}><option value="">Select plant</option>{plants.map(p=><option key={p._id} value={p._id}>{p.name}</option>)}</select></Field><Field label="Environment (optional)"><input value={form.environment} onChange={e=>set('environment',e.target.value)}/></Field></div><Field label="Category (optional)"><input value={form.category} onChange={e=>set('category',e.target.value)}/></Field><div className="ingredientEditor">{form.ingredients.map((x,i)=><div className="adminTwo" key={i}><Field label="Ingredient"><select required value={x.ingredientId} onChange={e=>updateIng(i,'ingredientId',e.target.value)}><option value="">Select ingredient</option>{ingredients.map(g=><option key={g._id} value={g._id}>{g.name}</option>)}</select></Field><Field label="Percentage"><input required type="number" min="0" max="100" step="0.01" value={x.percentage} onChange={e=>updateIng(i,'percentage',Number(e.target.value))}/></Field></div>)}</div><button type="button" className="btn ghost" onClick={()=>setForm(f=>({...f,ingredients:[...f.ingredients,{ingredientId:'',percentage:0}]}))}>+ Add ingredient</button><div className={`percentageTotal ${Math.abs(total-100)<.001?'valid':'invalid'}`}>Total: {total}% {Math.abs(total-100)<.001?'✓':'— must equal 100%'}</div><div className="adminModalActions"><button type="button" className="btn ghost" onClick={onClose}>Cancel</button><button className="btn primary">Save rule</button></div></form></Modal>}
function Inventory({rows,loading,search,setSearch,onStock}){return <section className="adminContent"><div className="adminTop"><div><span className="eyebrow">STOCK CONTROL</span><h1>Inventory</h1><p>Ingredient stock used by the Smart Mix engine.</p></div></div><Toolbar search={search} setSearch={setSearch}/><div className="adminTableWrap"><table className="adminTable"><thead><tr><th>Ingredient</th><th>Current</th><th>Minimum</th><th>Status</th><th>Actions</th></tr></thead><tbody>{loading?<tr><td colSpan="5">Loading...</td></tr>:rows.map(x=>{const low=x.stockQuantity<=x.minimumStock;return <tr key={x._id}><td><b>{x.name}</b></td><td>{x.stockQuantity} {x.unit}</td><td>{x.minimumStock} {x.unit}</td><td><span className={`statusPill ${low?'off':'on'}`}>{low?'Low stock':'Healthy'}</span></td><td><button className="smallAction" onClick={()=>onStock(x._id,'add')}>+ Add</button><button className="smallAction" onClick={()=>onStock(x._id,'remove')}>− Remove</button><button className="smallAction" onClick={()=>onStock(x._id,'set')}>Set</button></td></tr>})}</tbody></table></div></section>}
function OrdersAdmin({rows,loading,search,setSearch,status,setStatus,onChange}){return <section className="adminContent"><div className="adminTop"><div><span className="eyebrow">FULFILMENT</span><h1>Orders</h1><p>Review customer orders and update their status.</p></div></div><Toolbar search={search} setSearch={setSearch}/><div className="adminTableWrap"><table className="adminTable"><thead><tr><th>Order</th><th>Customer</th><th>Items</th><th>Total</th><th>Payment</th><th>Status</th><th>Update</th></tr></thead><tbody>{loading?<tr><td colSpan="7">Loading...</td></tr>:rows.map(o=><tr key={o._id}><td><b>#{o._id.slice(-7).toUpperCase()}</b><small>{new Date(o.createdAt).toLocaleDateString()}</small></td><td>{o.userId?.name}<small>{o.userId?.email}</small></td><td>{o.items.length}</td><td>{money(o.total)}</td><td>{o.paymentMethod}</td><td><span className="statusPill on">{o.status}</span></td><td><select value={status[o._id]||o.status} onChange={e=>setStatus(s=>({...s,[o._id]:e.target.value}))}><option>PENDING</option><option>CONFIRMED</option><option>PROCESSING</option><option>SHIPPED</option><option>DELIVERED</option><option>CANCELLED</option></select><button className="smallAction" onClick={()=>onChange(o._id)}>Save</button></td></tr>)}</tbody></table></div></section>}
function UsersAdmin({rows,loading,search,setSearch,onChange}){return <section className="adminContent"><div className="adminTop"><div><span className="eyebrow">CUSTOMERS</span><h1>Users</h1><p>Manage customer accounts.</p></div></div><Toolbar search={search} setSearch={setSearch}/><div className="adminTableWrap"><table className="adminTable"><thead><tr><th>Name</th><th>Email</th><th>Role</th><th>Orders</th><th>Spent</th><th>Status</th><th>Action</th></tr></thead><tbody>{loading?<tr><td colSpan="7">Loading...</td></tr>:rows.map(u=><tr key={u._id}><td><b>{u.name}</b></td><td>{u.email}</td><td>{u.role}</td><td>{u.orders}</td><td>{money(u.spent)}</td><td><span className={`statusPill ${u.active===false?'off':'on'}`}>{u.active===false?'Inactive':'Active'}</span></td><td><button className="smallAction" disabled={u.role==='ADMIN'} onClick={()=>onChange(u._id,u.active===false)}>{u.active===false?'Activate':'Deactivate'}</button></td></tr>)}</tbody></table></div></section>}
function Reports(){const [overview,setOverview]=useState(null),[sales,setSales]=useState([]),[mix,setMix]=useState([]);useEffect(()=>{Promise.all([adminApi.getReportOverview(),adminApi.getSalesReport(),adminApi.getCustomMixReport()]).then(([a,b,c])=>{setOverview(a.data);setSales(b.data);setMix(c.data)}).catch(()=>{});},[]);return <section className="adminContent"><div className="adminTop"><div><span className="eyebrow">ANALYTICS</span><h1>Reports</h1><p>Real MongoDB aggregation results.</p></div></div><div className="reportGrid">{[['Total sales',money(overview?.sales)],['Orders',overview?.orders||0],['Customers',overview?.customers||0],['Custom mix orders',overview?.customMixOrders||0]].map(x=><div className="reportCard" key={x[0]}><span>{x[0]}</span><strong>{x[1]}</strong></div>)}</div><div className="adminInsightGrid"><div className="adminCard"><h3>Monthly sales</h3>{sales.length?sales.map(x=><p key={`${x._id.year}-${x._id.month}`}>{x._id.year}/{x._id.month}: <b>{money(x.sales)}</b> · {x.orders} orders</p>):<p>No sales data yet.</p>}</div><div className="adminCard"><h3>Custom mix performance</h3>{mix.length?mix.map(x=><p key={x._id}>{x._id}: <b>{x.orders}</b> orders · {money(x.sales)}</p>):<p>No custom mix orders yet.</p>}</div></div></section>}
